### ISSUE TITLE
feat: Dynamic (Jinja) Markup / Templating

### ISSUE THREAD

**Issue by batonac** [frappe/builder#105]
Frappe framework provides both a server side and client side Jinja-API ([specially Html Templates In Javascript with a Jinja-like syntax](https://frappeframework.com/docs/user/en/guides/app-development/using-html-templates-in-javascript) on client-side). This would be really useful in Builder, both inside and outside the context of a repeater.

For a simple example, most website footers include a copyright statement including the current year. It would be great if we could render this dynamically in a single text block, such as:
```
© {{ now().year }} Your Company Name. All rights reserved.
```

Inside a repeater, this same principle could be used to apply on-the-fly formatting, prepends/appends, etc. This functionality should be available at least in the link and content attributes IMO.

**Comment by surajshetty3416** [comment]
You can already do this :)

https://github.com/frappe/builder/assets/13928957/8655671f-a252-4ff4-8e9b-bec893b2d638

```
© {{ frappe.utils.format_date(frappe.utils.now(), format_string="YYYY") }} Your Company Name. All rights reserved.
```
Your example can be achieved with above text

**Comment by batonac** [comment]
Wonderful! Is the use of Jinja inside repeater templates a separate issue? To say it another way, is it possible to render attributes of the current repeater data object using Jinja rather than only the "Data Key" settings?

**Comment by batonac** [comment]
I figured out my own question: For a repeater with Data Key from dataScript, Builder creates a loop var named `key_<repeater_data_key>`. So if your repeater Data Key is `products`, the current item is `key_products`, and can be used within jinja as: `/page/{{ key_products.name }}`
