### ISSUE TITLE
Feat: Custom Domain support with https

### ISSUE THREAD

**Issue by me-abdullahj** [frappe/builder#111]
We should be able to install and configure frappe builder on our custom domain with https support either with Let's Encrypt SSL or our custom SSL.

**Comment by batonac** [comment]
This is already possible and is entirely related to your setup of Frappe, not Frappe Builder specifically.

**Comment by me-abdullahj** [comment]
Official support is always better.

**Comment by batonac** [comment]
https://frappeframework.com/docs/user/en/bench/guides/lets-encrypt-ssl-setup

**Comment by me-abdullahj** [comment]
Isn't that for framework only?

**Comment by batonac** [comment]
Builder is just an app on top of the framework, and ultimately renders sites and pages with the core website functionality, so there's no meaningful delineation to be made here.

**Comment by me-abdullahj** [comment]
Alright, thank you for the clarification.
