### ISSUE TITLE
Bug: HTML Attributes inside components don't get inserted

### ISSUE THREAD

**Issue by the3dfox** [frappe/builder#147]
When I set a custom **HTML Attribute** inside a component, the properties get lost as soon as I import the component.
This probably also applies to **RAW STYLE**

![image](https://github.com/frappe/builder/assets/84663901/a982d2b7-86d3-4d88-9758-a95b441b6fb7)
![image](https://github.com/frappe/builder/assets/84663901/d2625a74-eba7-48a4-be9d-9c4b03587274)

**Comment by surajshetty3416** [comment]
@the3dfox do you see those attributes in the published page?

**Comment by the3dfox** [comment]
yes, the attributes get published, but not visible in the editor... I guess it is a usability/design-decision thing then, rather than a bug
