### ISSUE TITLE
Issue: Not able to duplicate builder component in frappe app

### ISSUE THREAD

**Issue by the3dfox** [frappe/builder#177]
When I try duplicating a component inside the frappe app, I get the following message:

![image](https://github.com/frappe/builder/assets/84663901/81bc39f3-e047-485a-b36f-027e1858a705)

**Comment by surajshetty3416** [comment]
@the3dfox If you are trying to make a new component with slight change in the existing one, you can follow this step

https://github.com/frappe/builder/assets/13928957/b325bf6c-79ef-4296-bb7d-63aece1e8ec6

**Comment by surajshetty3416** [comment]
should be resolved with https://github.com/frappe/builder/commit/92b4e334c31b1eb10ab95bc4eedc9ccf86455864
