### ISSUE TITLE
Builder doesn't install

### ISSUE THREAD

**Issue by EasternIndustries-IT** [frappe/builder#213]
Using Bench or app.json builder doesn't install or install correctly
using `docker exec -it root /bin/bash` in backend and` bench get-app builder`, `bench install-app builder` , `bench migrate`, restart docker only results in blank screen when going to ip:port/builder. If this method doesn't work why is it still in docs? 

using the apps.json just completly fails when doing `docker build`

**Comment by surajshetty3416** [comment]
https://docs.frappe.io/builder/setting-up

Updated Setup guide. You can try and let me know if you still face any issue.
