### ISSUE TITLE
Error when creating a page

### ISSUE THREAD

**Issue by omarjabr** [frappe/builder#215]
![Screenshot 2024-09-24 143630](https://github.com/user-attachments/assets/f21556d1-0a6c-48a3-8f53-2796c204bde9)

Frappe Builder: v1.x.x-develop () (develop)
ERPNext: v15.27.3 (version-15)
Frappe Framework: v15.23.0 (version-15)

**Comment by surajshetty3416** [comment]
@omarjabr You need to update Frappe Framework to resolve this issue.
