### ISSUE TITLE
reset.css loading over http instead of https

### ISSUE THREAD

**Issue by clayrisser** [frappe/builder#216]
I'm getting the following error when using frappe builder. It's preventing the styles from loading. My site is using https, but the assets from frappe builder are using http.

```
Mixed Content: The page at 'https://example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://example.com/assets/builder/reset.css?v=1'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by clayrisser** [comment]
Looks like I'm not the only one to face this issue.

https://discuss.frappe.io/t/frappe-builder-mixed-content-cant-use-https-reverse-proxy/127197

**Comment by surajshetty3416** [comment]
@clayrisser 

See if following command helps. (this is an escape hatch)
```
bench --site set-config ssl_certificate true
```

or else

you might have to setup HTTPs for your instance to avoid that.
https://frappeframework.com/docs/user/en/bench/guides/configuring-https

**Comment by clayrisser** [comment]
This did not fix it.

**Comment by clayrisser** [comment]
@surajshetty3416 the issue is caused by the `<base>` tag in the HTML document.

**Comment by clayrisser** [comment]
I resolved it by setting the`host_name` config.

**Comment by 0yeifer** [comment]
Thank you, @clayrisser, for sharing the solution! I'm just adding this comment to provide more details for others facing the same issue.

To fix the problem, you can run the following command:
```bash
bench --site [site-name] set-config host_name https://site-name-example.com
```

This updates the `site_config.json` file located at `frappe-bench/sites/[site-name]/site_config.json`, adding the `host_name` key with the correct HTTPS URL.

After making this change, ensure the updates take effect by running:
```
bench --site [site-name] clear-cache
```
Or restart bench

For more information about site_config.json and its usage, check the official documentation here:
[https://frappeframework.com/docs/user/en/basics/site_config](https://frappeframework.com/docs/user/en/basics/site_config)

Hope this helps!
