### ISSUE TITLE
frappe.get_doc data script AssertionError

### ISSUE THREAD

**Issue by Saleh-E** [frappe/builder#218]
now i put in data script
data.blog_info = frappe.get_doc(“blog post”, frappe.form_dict.blog_name or “sdsdsd fdf”)

its working because sdsdsd fdf is found but it fetch data for this doc only so when i do dynamic route and open any post open same page although url is change to serach specifi page but it found it self becaus i fetch by specifi name so i try by this as]
data.blog_info = frappe.get_doc(“blog post”, frappe.form_dict.blog_name)

when save data script save but this notification appear
There was an error while fetching page data AssertionError

and appear this eroor in console

POST [https://mysite.com/api/method/run_doc_method](javascript:void(0);) [HTTP/1.1 404 NOT FOUND 154ms] 

try any doctype same eroor try new way in documentation
data.property_info = frappe.get_doc(“Property”, “<smart_id>”)

same eroor i try every thing although i can fetch list datat but his noo
local i try aws i try with cors i try iam tiried from this and this last step to create my website

please give me solution iam sure is simple as usual of frappe but i don`t knew it

**Comment by surajshetty3416** [comment]
Resolved with https://github.com/frappe/builder/commit/6e0017a854a1443c2506a722369a7cc6f38a438c
