### ISSUE TITLE
Truncate page titles on Builder home page

### ISSUE THREAD

**Issue by nish7x** [frappe/builder#22]
To avoid wrapping. Maybe can show full title on hover in tooltip in case needed to differentiate between similar titles. 

<img width="1110" alt="image" src="https://github.com/frappe/builder/assets/8917840/7f5744c1-2fb5-4b3b-9b28-96fd2af3872a">

**Comment by surajshetty3416** [comment]
Already fixed with https://github.com/frappe/builder/commit/ede9b0fe6382c3c002dfe5a5da16644eb7defda3
