### ISSUE TITLE
Some specific browsing cases page access breaks

### ISSUE THREAD

**Issue by gupteshwar** [frappe/builder#221]
I was browsing through the Frappecloud.com, when I land in marketplace Tab and then to any specific App.
From there if I try access the Main Menu Item like Benefit or Feature or Pricing...
<img width="194" alt="Screenshot 2024-10-10 at 15 21 22" src="https://github.com/user-attachments/assets/19a57b47-4418-40af-9a1a-afcf65a26aa7">

Then I land up on broken Page.
<img width="1381" alt="Screenshot 2024-10-10 at 15 21 16" src="https://github.com/user-attachments/assets/3dc52de8-d10e-47a8-bf86-4bef591e5d80">

As Last parameter in URL just gets overwritten but the last detailed path in URI remains as previous.

**Comment by surajshetty3416** [comment]
Resolved by @nish7x 

--

Thanks @gupteshwar for reporting.
