### ISSUE TITLE
Mouse Wheel Zoom Out Bug

### ISSUE THREAD

**Issue by LynX-gh** [frappe/builder#225]
On the page builder page Ctrl + Mouse Wheel Down should only zoom out one level but it zooms out to the smallest percent. Ctrl + "-" and Ctrl + Mouse Wheel Down should behave the same

**Comment by surajshetty3416** [comment]
@LynX-gh I mostly use pinch zoom on trackpad and it works fine. Based on the code there is no special handling for mouse and zooming out... so ideally it should work fine with mouse as well.

Could it be related your scroll wheel ([give it test](https://fractalglider.github.io/fun/2018/02/13/testing-mouse-scroll-wheel.html))? If not can you share animated an GIF to understand the issue better.

**Comment by LynX-gh** [comment]
![Screen-Recording](https://github.com/user-attachments/assets/0cf8fbb1-ec2a-47c3-b9b0-cc8d43642864)
I tested my mouse the input on scroll down and scroll up is the same. On scroll down the page zooms out fully. In the gif the first 2 are using the scroll wheel and the last 2 zoom out are using the plus and minus keys.

**Comment by surajshetty3416** [comment]
@LynX-gh you were right... I tried with my old optical mouse and code was too sensitive for mouse wheel scroll.

https://github.com/frappe/builder/commit/24ed39be557d08e5b37372c6891edf490c8d8274 
In this I have tried to control zoom sensitivity with some basic heuristics

**Comment by LynX-gh** [comment]
Thanks for the quick fix @surajshetty3416 
It was unusable with a mouse
