### ISSUE TITLE
Link images from any folders

### ISSUE THREAD

**Issue by RoberAF** [frappe/builder#226]
So a couple teammates and I are learning frappe and builder, when pushing and pulling repos we realized the images that one person added weren't exported in the fixrtures so when someone else pulls it does so without any image, I tried creating a folder in our custom app just to store images there and then on the page put the path to that folder but it seems that builder only allows images from "sites\example.site\public\files" , is there any way around this? Thanks in advance

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by bdalmonico** [comment]
You can use the public folder of your custom_app to store images that will be used throughout the application. Create an images folder --> apps/custom_app/public/images and upload the necessary images there.
These images will be available via the route /assets/custom_app/images/test.png.
