### ISSUE TITLE
[UX] Text selection area needs to be increased 

### ISSUE THREAD

**Issue by nish7x** [frappe/builder#229]
https://github.com/user-attachments/assets/5699858b-f65e-4012-86d1-b7f1e37c1eca

If you highlight something even a little past the text box, the parent gets selected. Needs to be done very accurately, so slows you down.

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
