### ISSUE TITLE
Feature Req: Ability to pan the design with a mouse

### ISSUE THREAD

**Issue by LynX-gh** [frappe/builder#231]
Currently I can only pan the design page using the arrow keys or a trackpad.
Maybe you could add the ability to pan the screen in the same way when holding right click and dragging the page

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by surajshetty3416** [comment]
@LynX-gh You can hit spacebar and drag the page.
