### ISSUE TITLE
background-color set from Data Script working in editor but not in preview or published version

### ISSUE THREAD

**Issue by florianbrochard** [frappe/builder#247]
Background color is correctly set from Data Script when editing my page. But it does not work on previewed or published page.

I am setting the `background-color` from Data Script result to a container this way :
![bulder Data Key](https://github.com/user-attachments/assets/cc00248d-2068-40a5-b155-030a88afb6f3)

It is working when editing my page :
![Attachment](https://github.com/user-attachments/assets/048d01ea-41a1-47d5-8905-f0c31aed2d88)
You can see top bar background from each items are colored based on the category.

But it does not work when published or previewed. It keeps it's default color (or none if no background-color is set from editor)
![Unknown](https://github.com/user-attachments/assets/b6bf658e-bd09-43d9-9d95-f68b5a281fa7)

I try many things but it seems there is a bug.

#### Result from Data Script
```
"events": [
    {
      "subject": "Atelier groupe de parole / philo",
      "starts_on": "2024-11-09 14:30:00",
      "image": "/files/Capture d’écran 2024-10-14 à 16.07.23.png",
      "route": "events/EV00021-atelier-groupe-de-parole-philo",
      "custom_categorie": "Culture",
      "registration_amount": 0,
      "allow_registrations": 0,
      "date": "09/11/24 - 14h30",
      "icon": "/files/Culture.svg",
      "color": "#c697fc"
    },
```

**Comment by surajshetty3416** [comment]
@florianbrochard Thanks for reporting. It was indeed a bug... fixed with [this commit](https://github.com/frappe/builder/commit/f4f27e03ea07257047b1e3f39d37c4f8a081437c).
