### ISSUE TITLE
Client Script and Data Script in Frappe Builder Lack Clarity

### ISSUE THREAD

**Issue by engahmed1190** [frappe/builder#250]
Description:

The functionality and usage of Client Script and Data Script in the Frappe Builder are unclear, making it difficult for users to understand how to effectively implement and customize scripts for their specific needs. This lack of clarity impacts the overall user experience and hinders productivity.

![image](https://github.com/user-attachments/assets/3e0e41f0-618b-4c28-a8d5-e0aadd515005)

**Comment by surajshetty3416** [comment]
Hi, [this change should fix](https://github.com/frappe/builder/pull/249) the issue.

**Comment by engahmed1190** [comment]
Thanks @surajshetty3416 . I will test it on the pull request branch and also check my local branch.

**Comment by surajshetty3416** [comment]
Resolved with https://github.com/frappe/builder/pull/249
