### ISSUE TITLE
Builder UI elements background, not showing

### ISSUE THREAD

**Issue by IvanGuevaraM** [frappe/builder#251]
Hi folks,

Is it just me or is it general that the background of the Builder UI isn´t showing?

![frappe_builder_main](https://github.com/user-attachments/assets/b2fec08c-60ee-4fd6-b844-9ba5b26f5bf4)

![frappe_builder_page_edition](https://github.com/user-attachments/assets/180e9a89-7abb-448f-b468-d62682584e9a)

Regards.

**Comment by surajshetty3416** [comment]
@IvanGuevaraM which version are you using? The issue has been fixed with [this](https://github.com/frappe/builder/pull/249).

**Comment by IvanGuevaraM** [comment]
This one...
![builder_developer_1 x x-develop](https://github.com/user-attachments/assets/a879fe96-5889-4f5a-b078-e88d2951a20a)

**Comment by surajshetty3416** [comment]
Updating builder should fix the issue.
