### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by rnd-nguyenth** [frappe/builder#263]
Hi folks,

I am not able to upload images on both version:  v1.x.x-develop () (develop) and v1.12.5 (master) on a fresh installation frappe.
Getting bellow error:
![image](https://github.com/user-attachments/assets/85b9dd40-2070-40a5-bcd0-5b130a7b44be)
I have run bench migrate and check storage capacity, but it seems ok
![image](https://github.com/user-attachments/assets/20407cc6-c2af-4a07-8987-8e95e6f84141)

**Comment by surajshetty3416** [comment]
@rnd-nguyenth Can you share the steps you followed to install Builder?

Because, ideally that folder is supposed to get created during installation. ([ref](https://github.com/frappe/builder/blob/develop/builder/install.py#L7))

**Comment by rnd-nguyenth** [comment]
Hi @surajshetty3416 , thank you for looking into this. I installed frappe following https://github.com/flexcomng/erpnext_quick_install a while ago without any error. Yesterday, I revisited the site and installed Builder for testing purpose and encountered this issue. 

After creating "Builder Uploads" folder, I am able to upload images. Thanks.

BTW, learned so much from your Frappe Builder in action with Hussain. Great Work !!! I am looking forward for new videos on building sign up and login pages...

**Comment by surajshetty3416** [comment]
>I installed frappe following [flexcomng/erpnext_quick_install](https://github.com/flexcomng/erpnext_quick_install?rgh-link-date=2024-12-13T01%3A59%3A06Z) a while ago without any error.

Alright, since this is not our standard installation script and we do not have enough info on what went wrong, can't really do much about this. If you find any related log to investigate this further, do let me know.
