### ISSUE TITLE
add favicon and client script in builder

### ISSUE THREAD

**Issue by aaguirrek** [frappe/builder#37]
It would be nice to have the option to add the client scripts from the builder as well as a place where you can change the favicon

**Comment by surajshetty3416** [comment]
@aaguirrek you can already add client scripts. Currently it toggle using "ctrl + `" shortcut ref: https://github.com/frappe/builder/pull/13

you can use script to add favicon but yeah, we can have a standard setting to set favicon

**Comment by surajshetty3416** [comment]
https://github.com/frappe/builder/pull/151

@aaguirrek We now have the option to set favicon per page
