### ISSUE TITLE
Integration of plasmic.app as page builder

### ISSUE THREAD

**Issue by stephenBDT** [frappe/builder#43]
I was wondering, if we would gain more from implementing and integration plasmic into frappe using also frappe-ui and the frappe react sdk.

The recently open-sourced their whole application and say that it could well integrate with existing codebases:
https://plasmic.app/

What do you think about it

**Comment by surajshetty3416** [comment]
@stephenBDT Plasmic is a really good tool for site building but I am not sure if plasmic's complete visual builder is open source... based on what I checked, it seems it let's you sync the project changes done on the studio (their page editor) to your local which means you are still tied to [studio.plasmic.app](studio.plasmic.app). I don't see it helping Frappe apps without complex setup (please share if you have more insights).

On the other hand, Builder is a Frappe app, which means you can directly install it on existing frappe sites and instantly start building and publishing web pages. It is also very easy with to load and render data that exists in your frappe sites to your websites using "Data Script" feature.

Of-course, builder currently has limited functionalities, but lot's of exciting features have been planned for builder to make website page building experience easier and fun.
