### ISSUE TITLE
Handle exception when data script fails

### ISSUE THREAD

**Issue by rmehta** [frappe/builder#45]
<img width="657" alt="Screenshot 2024-01-03 at 3 09 45 PM" src="https://github.com/frappe/builder/assets/140076/e6394272-451c-41b5-8677-574175773641">

![telegram-cloud-photo-size-4-5814456743583924818-y](https://github.com/frappe/builder/assets/140076/c250d158-4f7e-46ee-97cf-c8152765c06b)

**Comment by surajshetty3416** [comment]
Fixed with https://github.com/frappe/builder/commit/7c2bfce19c63eb815521af09ae8e2c17e3aa0c21
