### ISSUE TITLE
need side panels to be scrollable

### ISSUE THREAD

**Issue by jalajc** [frappe/builder#5]
The side panel css should be scrollable. Need to remove no-scroll class from (right) side block.

**Comment by surajshetty3416** [comment]
@jalajc Is you concern related to accessibility? Or are you not able to scroll side panels?

**Comment by jalajc** [comment]
> @jalajc Is your concern related to accessibility? Or are you not able to scroll side panels?

Side panel is lengthy...I was not able to scroll on laptop (with just touchpad). Later I see it works with mouse scroll button.
Ideally a slick scroll bar should be there.

**Comment by surajshetty3416** [comment]
Closing this for now as this seems like a non-issue
