### ISSUE TITLE
For Linux and Windows user, change undo to ctrl+z instead of windows+z

### ISSUE THREAD

**Issue by the3dfox** [frappe/builder#51]
for windows and linux user the common combination is ctrl+key instead of windows+key
Or give the option to bind keys, to get your own combinations

**Comment by surajshetty3416** [comment]
@the3dfox Please update and try again

**Comment by the3dfox** [comment]
@surajshetty3416 I checked the fix, the implementation kinda works. Strangely, it only recognizes every second input. So to undo I need to press ctrl+z two times.
Checked with 121.0 (64-bit) and Brave [Version 1.61.114]
Duplication ctrl+d on the other hand works as expected

**Comment by surajshetty3416** [comment]
Might be some issue with history management 🤔 

Can you share a GIF so that I can get more clarity on what's going on?

**Comment by the3dfox** [comment]
![test](https://github.com/frappe/builder/assets/84663901/69b8703a-789c-4efc-9c89-c45d1017d2f0)
