### ISSUE TITLE
Bug: Unable to delete element copied from component

### ISSUE THREAD

**Issue by the3dfox** [frappe/builder#74]
Today by accident, I copied or duplicated an element from a component to use in a different context.
Problem is, I can not move or delete this element in the element tree on the left or in the canvas itself. Whenever I try, I get the following message:

![image](https://github.com/frappe/builder/assets/84663901/2af7aa37-c4b6-46db-be9e-2788cefe60d8)

this is how it looks in the tree view:
![image](https://github.com/frappe/builder/assets/84663901/d6fb9fa7-161d-4321-b626-2ef2df456ebd)

Should be very easy to reproduce, I think solution could be, not allowing to copy single elements from components or detaching the element from the component if you do so. Otherwise, we would probably need a better component-element to element linking

**Comment by surajshetty3416** [comment]
Should not happen again after https://github.com/frappe/builder/pull/77. 

---

To resolve your current state you can use "Wrap in container" and delete that container (workaround)
