### ISSUE TITLE
Attach script dropdown list isn't scrollable 

### ISSUE THREAD

**Issue by nish7x** [frappe/builder#80]
<img width="1440" alt="image" src="https://github.com/frappe/builder/assets/8917840/ea0f87d8-b36d-4993-9317-df60df3c0460">

Overflows off the screen if list is too long. Cannot scroll with the mouse wheel or any visible scrollbars.

**Comment by surajshetty3416** [comment]
fix with https://github.com/frappe/builder/commit/454c79c51924b1fcdadc61d53e7b3771b9057d6e
