### ISSUE TITLE
Bug: preview issues using components inside components

### ISSUE THREAD

**Issue by the3dfox** [frappe/builder#85]
I encountered an issue using a component inside a component. For instance, creating a component called headline and using this component inside a second component
![image](https://github.com/frappe/builder/assets/84663901/31c3e8d9-5c89-4127-b76d-7927b42d8885)

This leads to the following problem:
1. Component not rendered in editor canvas. In the preview, it is rendered correctly though
![image](https://github.com/frappe/builder/assets/84663901/ddfece84-e364-4db5-878b-6138c0ff9256)

**Comment by batonac** [comment]
I'm experiencing issues with this as well. In my case, components nested within a component are visible on the pages where they're present, but do not display the attribute overrides in the page-edit context.

For example, I have here a simple header component which contains menu links as sub-components. As you can see, the default sub-component text is displayed on the page edit view:
![image](https://github.com/frappe/builder/assets/4996285/0c61e47e-d212-4287-9029-b6d02320d72d)

In the component editor the component-level attribute overrides are rendered correctly:
![image](https://github.com/frappe/builder/assets/4996285/6bc74863-6787-4ec8-a3dd-20e7174d390e)

They're also just fine on the rendered frontend:
![image](https://github.com/frappe/builder/assets/4996285/be1ed040-cbde-4688-b042-6630786ecf0e)

In the end, this doesn't impede development, but it is annoying.
