### ISSUE TITLE
Feat: Unable to reset/unset placement setting within a container

### ISSUE THREAD

**Issue by the3dfox** [frappe/builder#88]
Currently, there is no way to reset the placement setting within a container
![image](https://github.com/frappe/builder/assets/84663901/6911b04c-3ef0-4b5b-a958-1da7d74aba8e)

As soon as you select a certain placement, there is no way to reset the placement setting to "nothing" or unset

**Comment by surajshetty3416** [comment]
@the3dfox You can now click on placement box again to unset the placement.
